# Generated by Django 5.1.2 on 2024-10-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
    ]
